"""Add route fields

Revision ID: ff3f9e5acef3
Revises: fa45a0f35414
Create Date: 2026-02-08 15:32:00.462697

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff3f9e5acef3'
down_revision: Union[str, Sequence[str], None] = 'fa45a0f35414'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rides', sa.Column('route_polyline', sa.String(length=5000), nullable=True))
    op.add_column('rides', sa.Column('status', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rides', 'status')
    op.drop_column('rides', 'route_polyline')
    # ### end Alembic commands ###
